// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240724182255_Migracion4")]
    partial class Migracion4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId");

                    b.HasIndex("GradoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            AlumnoId = 1,
                            Apellido = "Pérez",
                            CodigoPostal = "2000",
                            Dni = "12345678",
                            Domicilio = "San Martin 1234",
                            Estado = 0,
                            FechaNacimiento = new DateTime(2005, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradoId = 1,
                            Localidad = "Rosario",
                            Nombre = "Juan",
                            Pais = "Argentina",
                            Provincia = "Santa Fe",
                            Sexo = 0
                        },
                        new
                        {
                            AlumnoId = 2,
                            Apellido = "Gómez",
                            CodigoPostal = "1406",
                            Dni = "23456789",
                            Domicilio = "Calle 5 de Mayo 567",
                            Estado = 0,
                            FechaNacimiento = new DateTime(2006, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradoId = 2,
                            Localidad = "Buenos Aires",
                            Nombre = "María",
                            Pais = "Argentina",
                            Provincia = "Buenos Aires",
                            Sexo = 1
                        });
                });

            modelBuilder.Entity("Entidades.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo1")
                        .HasColumnType("int");

                    b.Property<int>("TrimestreId")
                        .HasColumnType("int");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("TrimestreId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("Entidades.DetalleCalificaciones", b =>
                {
                    b.Property<int>("DetalleCalificacionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCalificacionesId"));

                    b.Property<string>("CodDetalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int>("LibroAlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("DetalleCalificacionesId");

                    b.HasIndex("ExamenId");

                    b.HasIndex("LibroAlumnoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("DetallesDeCalificaciones");
                });

            modelBuilder.Entity("Entidades.Examen", b =>
                {
                    b.Property<int>("ExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamenId"));

                    b.Property<int>("Tipo1")
                        .HasColumnType("int");

                    b.Property<int>("TrimestreId")
                        .HasColumnType("int");

                    b.HasKey("ExamenId");

                    b.HasIndex("TrimestreId");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("Entidades.Grado", b =>
                {
                    b.Property<int>("GradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradoId"));

                    b.Property<int>("CantidadMaterias")
                        .HasColumnType("int");

                    b.Property<int>("Especialidad")
                        .HasColumnType("int");

                    b.Property<int>("NumGrado")
                        .HasColumnType("int");

                    b.HasKey("GradoId");

                    b.ToTable("Grados");

                    b.HasData(
                        new
                        {
                            GradoId = 1,
                            CantidadMaterias = 8,
                            Especialidad = 0,
                            NumGrado = 1
                        },
                        new
                        {
                            GradoId = 2,
                            CantidadMaterias = 10,
                            Especialidad = 0,
                            NumGrado = 2
                        },
                        new
                        {
                            GradoId = 3,
                            CantidadMaterias = 10,
                            Especialidad = 0,
                            NumGrado = 3
                        },
                        new
                        {
                            GradoId = 4,
                            CantidadMaterias = 11,
                            Especialidad = 2,
                            NumGrado = 4
                        },
                        new
                        {
                            GradoId = 5,
                            CantidadMaterias = 11,
                            Especialidad = 2,
                            NumGrado = 5
                        },
                        new
                        {
                            GradoId = 6,
                            CantidadMaterias = 10,
                            Especialidad = 2,
                            NumGrado = 6
                        });
                });

            modelBuilder.Entity("Entidades.LibroAlumno", b =>
                {
                    b.Property<int>("LibroAlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("LibroAlumnoId");

                    b.ToTable("LibrosAlumnos");

                    b.HasDiscriminator().HasValue("LibroAlumno");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entidades.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<string>("CodigoMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Especialidad1")
                        .HasColumnType("int");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.Property<int>("HorasAnuales")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MateriaId");

                    b.HasIndex("GradoId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            CodigoMateria = "A01",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Ciencias Naturales"
                        },
                        new
                        {
                            MateriaId = 2,
                            CodigoMateria = "A02",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Ciencias Sociales"
                        },
                        new
                        {
                            MateriaId = 3,
                            CodigoMateria = "A03",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Artística"
                        },
                        new
                        {
                            MateriaId = 4,
                            CodigoMateria = "A04",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 5,
                            CodigoMateria = "A05",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 6,
                            CodigoMateria = "A06",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 7,
                            CodigoMateria = "A07",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Prácticas del Lenguaje"
                        },
                        new
                        {
                            MateriaId = 8,
                            CodigoMateria = "A08",
                            Especialidad1 = 0,
                            GradoId = 1,
                            HorasAnuales = 0,
                            NombreMateria = "Construcción de Ciudadanía"
                        },
                        new
                        {
                            MateriaId = 9,
                            CodigoMateria = "B01",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Biología"
                        },
                        new
                        {
                            MateriaId = 10,
                            CodigoMateria = "B02",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Construcción de Ciudadanía"
                        },
                        new
                        {
                            MateriaId = 11,
                            CodigoMateria = "B03",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Artística"
                        },
                        new
                        {
                            MateriaId = 12,
                            CodigoMateria = "B04",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 13,
                            CodigoMateria = "B05",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Físico Química"
                        },
                        new
                        {
                            MateriaId = 14,
                            CodigoMateria = "B06",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Geografía"
                        },
                        new
                        {
                            MateriaId = 15,
                            CodigoMateria = "B07",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Historia"
                        },
                        new
                        {
                            MateriaId = 16,
                            CodigoMateria = "B08",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 17,
                            CodigoMateria = "B09",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 18,
                            CodigoMateria = "B10",
                            Especialidad1 = 0,
                            GradoId = 2,
                            HorasAnuales = 0,
                            NombreMateria = "Prácticas del Lenguaje"
                        },
                        new
                        {
                            MateriaId = 19,
                            CodigoMateria = "C01",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Biología"
                        },
                        new
                        {
                            MateriaId = 20,
                            CodigoMateria = "C02",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Construcción de Ciudadanía"
                        },
                        new
                        {
                            MateriaId = 21,
                            CodigoMateria = "C03",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Artística"
                        },
                        new
                        {
                            MateriaId = 22,
                            CodigoMateria = "C04",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 23,
                            CodigoMateria = "C05",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Físico Química"
                        },
                        new
                        {
                            MateriaId = 24,
                            CodigoMateria = "C06",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Geografía"
                        },
                        new
                        {
                            MateriaId = 25,
                            CodigoMateria = "C07",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Historia"
                        },
                        new
                        {
                            MateriaId = 26,
                            CodigoMateria = "C08",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 27,
                            CodigoMateria = "C09",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 28,
                            CodigoMateria = "C10",
                            Especialidad1 = 0,
                            GradoId = 3,
                            HorasAnuales = 0,
                            NombreMateria = "Prácticas del Lenguaje"
                        },
                        new
                        {
                            MateriaId = 29,
                            CodigoMateria = "D01",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 30,
                            CodigoMateria = "D02",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Literatura"
                        },
                        new
                        {
                            MateriaId = 31,
                            CodigoMateria = "D03",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 32,
                            CodigoMateria = "D04",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 33,
                            CodigoMateria = "D05",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Salud y Adolescencia"
                        },
                        new
                        {
                            MateriaId = 34,
                            CodigoMateria = "D06",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Biología"
                        },
                        new
                        {
                            MateriaId = 35,
                            CodigoMateria = "D07",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Historia"
                        },
                        new
                        {
                            MateriaId = 36,
                            CodigoMateria = "D08",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Geografía"
                        },
                        new
                        {
                            MateriaId = 37,
                            CodigoMateria = "D09",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "NTICx"
                        },
                        new
                        {
                            MateriaId = 38,
                            CodigoMateria = "D10",
                            Especialidad1 = 0,
                            GradoId = 4,
                            HorasAnuales = 0,
                            NombreMateria = "Psicología"
                        },
                        new
                        {
                            MateriaId = 39,
                            CodigoMateria = "E01",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 40,
                            CodigoMateria = "E02",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Literatura"
                        },
                        new
                        {
                            MateriaId = 41,
                            CodigoMateria = "E03",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 42,
                            CodigoMateria = "E04",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 43,
                            CodigoMateria = "E05",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Política y Ciudadanía"
                        },
                        new
                        {
                            MateriaId = 44,
                            CodigoMateria = "E06",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Introducción a la Química"
                        },
                        new
                        {
                            MateriaId = 45,
                            CodigoMateria = "E07",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Comunicación, Cultura y Sociedad"
                        },
                        new
                        {
                            MateriaId = 46,
                            CodigoMateria = "E08",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Historia"
                        },
                        new
                        {
                            MateriaId = 47,
                            CodigoMateria = "E09",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Geografía"
                        },
                        new
                        {
                            MateriaId = 48,
                            CodigoMateria = "E10",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Economía Política"
                        },
                        new
                        {
                            MateriaId = 49,
                            CodigoMateria = "E11",
                            Especialidad1 = 0,
                            GradoId = 5,
                            HorasAnuales = 0,
                            NombreMateria = "Sociología"
                        },
                        new
                        {
                            MateriaId = 50,
                            CodigoMateria = "F01",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Matemática"
                        },
                        new
                        {
                            MateriaId = 51,
                            CodigoMateria = "F02",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Literatura"
                        },
                        new
                        {
                            MateriaId = 52,
                            CodigoMateria = "F03",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Educación Física"
                        },
                        new
                        {
                            MateriaId = 53,
                            CodigoMateria = "F04",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Inglés"
                        },
                        new
                        {
                            MateriaId = 54,
                            CodigoMateria = "F05",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Trabajo y Ciudadanía"
                        },
                        new
                        {
                            MateriaId = 55,
                            CodigoMateria = "F06",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Proyecto de Investigación en Ciencias Sociales"
                        },
                        new
                        {
                            MateriaId = 56,
                            CodigoMateria = "F07",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Historia"
                        },
                        new
                        {
                            MateriaId = 57,
                            CodigoMateria = "F08",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Geografía"
                        },
                        new
                        {
                            MateriaId = 58,
                            CodigoMateria = "F09",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Arte"
                        },
                        new
                        {
                            MateriaId = 59,
                            CodigoMateria = "F10",
                            Especialidad1 = 0,
                            GradoId = 6,
                            HorasAnuales = 0,
                            NombreMateria = "Filosofía"
                        });
                });

            modelBuilder.Entity("Entidades.Trimestre", b =>
                {
                    b.Property<int>("TrimestreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrimestreId"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("CodTrimestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasTotalesHabiles")
                        .HasColumnType("int");

                    b.Property<int>("NumTrimestre")
                        .HasColumnType("int");

                    b.HasKey("TrimestreId");

                    b.ToTable("Trimestres");
                });

            modelBuilder.Entity("Entidades.LibroDeAsistencias", b =>
                {
                    b.HasBaseType("Entidades.LibroAlumno");

                    b.Property<decimal>("PorcentajeAsistenciaTrimestre1")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("PorcentajeAsistenciaTrimestre2")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("PorcentajeAsistenciaTrimestre3")
                        .HasColumnType("decimal(4, 1)");

                    b.HasDiscriminator().HasValue("LibroDeAsistencias");

                    b.HasData(
                        new
                        {
                            LibroAlumnoId = 3,
                            AlumnoId = 1,
                            PorcentajeAsistenciaTrimestre1 = 0m,
                            PorcentajeAsistenciaTrimestre2 = 0m,
                            PorcentajeAsistenciaTrimestre3 = 0m
                        },
                        new
                        {
                            LibroAlumnoId = 4,
                            AlumnoId = 2,
                            PorcentajeAsistenciaTrimestre1 = 0m,
                            PorcentajeAsistenciaTrimestre2 = 0m,
                            PorcentajeAsistenciaTrimestre3 = 0m
                        });
                });

            modelBuilder.Entity("Entidades.LibroDeCalificaciones", b =>
                {
                    b.HasBaseType("Entidades.LibroAlumno");

                    b.Property<decimal>("NotaFinalAnual")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("NotaTrimestre1")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("NotaTrimestre2")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal>("NotaTrimestre3")
                        .HasColumnType("decimal(4, 1)");

                    b.HasDiscriminator().HasValue("LibroDeCalificaciones");

                    b.HasData(
                        new
                        {
                            LibroAlumnoId = 1,
                            AlumnoId = 1,
                            NotaFinalAnual = 0m,
                            NotaTrimestre1 = 0m,
                            NotaTrimestre2 = 0m,
                            NotaTrimestre3 = 0m
                        },
                        new
                        {
                            LibroAlumnoId = 2,
                            AlumnoId = 2,
                            NotaFinalAnual = 0m,
                            NotaTrimestre1 = 0m,
                            NotaTrimestre2 = 0m,
                            NotaTrimestre3 = 0m
                        });
                });

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.HasOne("Entidades.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Entidades.Asistencia", b =>
                {
                    b.HasOne("Entidades.Trimestre", "Trimestre")
                        .WithMany()
                        .HasForeignKey("TrimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trimestre");
                });

            modelBuilder.Entity("Entidades.DetalleCalificaciones", b =>
                {
                    b.HasOne("Entidades.Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.LibroDeCalificaciones", "LibroDeCalificaciones")
                        .WithMany("DetallesCalificaciones")
                        .HasForeignKey("LibroAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("LibroDeCalificaciones");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Entidades.Examen", b =>
                {
                    b.HasOne("Entidades.Trimestre", "Trimestre")
                        .WithMany()
                        .HasForeignKey("TrimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trimestre");
                });

            modelBuilder.Entity("Entidades.Materia", b =>
                {
                    b.HasOne("Entidades.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Entidades.LibroDeAsistencias", b =>
                {
                    b.HasOne("Entidades.Alumno", "Alumno")
                        .WithOne("LibroDeAsistencias")
                        .HasForeignKey("Entidades.LibroDeAsistencias", "LibroAlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Entidades.LibroDeCalificaciones", b =>
                {
                    b.HasOne("Entidades.Alumno", "Alumno")
                        .WithOne("LibroDeCalificaciones")
                        .HasForeignKey("Entidades.LibroDeCalificaciones", "LibroAlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Entidades.Alumno", b =>
                {
                    b.Navigation("LibroDeAsistencias")
                        .IsRequired();

                    b.Navigation("LibroDeCalificaciones")
                        .IsRequired();
                });

            modelBuilder.Entity("Entidades.LibroDeCalificaciones", b =>
                {
                    b.Navigation("DetallesCalificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
